version: '3.4'
services:
  jira:
    image: haxqer/jira:9.14.1
    container_name: jira-srv
    environment:
      - TZ=Asia/Shanghai
      - JVM_MINIMUM_MEMORY=1g
      - JVM_MAXIMUM_MEMORY=6g
      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=4g'
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - /home/revotech/data/jira:/var/jira
    restart: always
    networks:
      - network-bridge

  confluence:
    image: haxqer/confluence:8.8.1
    container_name: confluence-srv
    environment:
      - TZ=Asia/Shanghai
      - JVM_MINIMUM_MEMORY=1g
      - JVM_MAXIMUM_MEMORY=6g
      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=4g'
    depends_on:
      - mysql
    ports:
      - "8090:8090"
    volumes:
      - /home/revotech/data/confluence:/var/confluence
    restart: always
    networks:
      - network-bridge

  mysql:
    image: mysql:8.0
    container_name: mysql-jira
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=jira
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=jira
      - MYSQL_PASSWORD=123123
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    ports:
      - "13306:3306"
    volumes:
      - /home/revotech/data/mysql_data_jira:/var/lib/mysql
    restart: always
    networks:
      - network-bridge

  mysql-confluence:
    image: mysql:8.0
    container_name: mysql-confluence
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=confluence
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=confluence
      - MYSQL_PASSWORD=123123
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin', '--transaction-isolation=READ-COMMITTED', '--innodb_log_file_size=256M', '--max_allowed_packet=256M','--log_bin_trust_function_creators=1']
    volumes:
      - /home/revotech/data/mysql_data_confluence:/var/lib/mysql
    ports:
      - "13307:3306"
    restart: always
    networks:
      - network-bridge

networks:
  network-bridge:
    external: true
    name: revotech
